
### Edge: User can set empty name "" in profile (if allowed by API)
PUT {{baseUrl}}/api/v1/customer/profile
Authorization: {{authUser}}
Accept: {{accept}}
Content-Type: application/json

{
  "name": ""
}
